version: '3'
services:
  postgres:
    image: postgres
    build: 
      dockerfile: postgres/Dockerfile
      context: .
    container_name: my-postgres
    env_file:
      - .env
    ports:
      - "5432:5432"
    shm_size: '256MB'
    tty: true
    stdin_open: true
  vault:
    image: vault
    build: 
      dockerfile: vault/Dockerfile
      context: .
    container_name: my-vault
    ports:
      - "8200:8200"
    cap_add:
      - IPC_LOCK
    tty: true
    stdin_open: true
    depends_on:
      - postgres
    env_file:
      - .env
    volumes:
      - ./vault/file:/vault/file:rw
      - ./vault/config:/vault/config:rw
    entrypoint: vault server -dev -config=/vault/config/vault.json
    # entrypoint: sh -c "/startup.sh"